environment:
  ADDON: pvr.hdhomerun
  ROOT: c:\projects

  matrix:
    - CMAKE_GENERATOR: Visual Studio 14 2015
      CONFIG: Debug
    - CMAKE_GENERATOR: Visual Studio 14 2015
      CONFIG: Release
    - CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Debug
    - CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      CONFIG: Release

# clone directory
clone_folder: c:\projects\%ADDON%

install:
  # Make unix-compatible patch.exe available to the build by copying it from
  # Git\usr\bin (that we remove from PATH) to another directory and adding it to
  # PATH; 
  - mkdir "C:\Program Files\PatchFromGit"
  - ps: copy "C:\Program Files\Git\usr\bin\patch.exe" "C:\Program Files\PatchFromGit"
  - ps: copy "C:\Program Files\Git\usr\bin\msys*.dll" "C:\Program Files\PatchFromGit"
  - set PATH=C:\Program Files\PatchFromGit;%PATH%

init:
  - echo ADDON=%ADDON%
  - echo CONFIG=%CONFIG%
  - echo CMAKE_GENERATOR=%CMAKE_GENERATOR%
  - cmake --version
  - msbuild /version
  - git --version
  - git clone --depth=1 https://github.com/xbmc/xbmc.git %ROOT%\xbmc
  
build_script:
  - mkdir %ROOT%\%ADDON%\build
  - cd %ROOT%\%ADDON%\build
  - cmake -G "%CMAKE_GENERATOR%" -DADDONS_TO_BUILD=%ADDON% -DCMAKE_BUILD_TYPE=%CONFIG% -DADDON_SRC_PREFIX=%ROOT% -DCMAKE_INSTALL_PREFIX=%ROOT%\xbmc\addons -DCMAKE_USER_MAKE_RULES_OVERRIDE=%ROOT%\xbmc\cmake\scripts\windows\CFlagOverrides.cmake -DCMAKE_USER_MAKE_RULES_OVERRIDE_CXX=%ROOT%\xbmc\cmake\scripts\windows\CXXFlagOverrides.cmake -DPACKAGE_ZIP=1 %ROOT%\xbmc\cmake\addons
  - cmake --build . --config %CONFIG%
